// placeholder file

const tags = [
  "bakemonogatari",
  "scenery",
  "action",
  "dialogue",
  "still",
  "text",
  "card",
  "shaft moment",
  "araragi koyomi",
  "araragi karen",
  "araragi tsukihi",
  "senjougahara hitagi",
  "sengoku nadeko",
  "kaiki deishuu",
  "gaen tooe",
  "gaen izuko",
  "kanbaru suruga",
  "hanekawa tsubasa",
  "burakku hanekawa",
  "oshino meme",
  "oshino shinobu",
  "kiss-shot acerola-orion heart-under-blade",
  "oshino ougi",
  "ononoki yotsugi",
  "hachikuji mayoi",
  "needs merge",
  "post episode",
  "duplicate",
  "op",
  "ed",
  "letterbox",
  "bake orange",
  "gore",
  "blood",
  "ecchi",
  "school",
  "park",
  "forest",
  "city",
  "araragi residence",
  "staple staple",
  "senjougahara residence",
  "kanbaru residence",
].sort();

export default tags;
